### ISSUE TITLE
pwkit_env.tar.gz 文件链接无法打开；2.0版解压后发现版本号还是1.0

### ISSUE THREAD

**Issue by LePingKYXK** [LonxunQuantum/pwkit#1]
在 `README.md` 中提到

> 如果你进行 1.1 安装步骤 部分时，没有找到 pwkit_env.tar.gz 文件，你可以通过如下方式下载：
> intel版本：[https://www.jianguoyun.com/p/DfhQFx8Q_qS-CxifgfwEIAA，提取码为](https://www.jianguoyun.com/p/DfhQFx8Q_qS-CxifgfwEIAA%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81%E4%B8%BA) lxkt

但是链接已经失效，无法打开。没有 pwkit_env 里的 conda 环境，pwkit 无法正常安装和使用。

另外，在页面的 `release` 里标记的是 **v2.0**。但是，下载并解压后，发现 `asset/logo.sh`, `env/pwkit` 里的版本号依旧是 **1.0**。
请问，此页面发布的版本到底是 1.0 还是 2.0 版呢？

**Comment by tianhongzhen** [comment]
We have already modified the download link and the version number issue in the logo.sh file.
